/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe.
         * @description The one endpoint that still answers while `MAINTENANCE=1`.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/update/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What should this node run?
         * @description Always `200` with a body. A withheld update, an up-to-date node, an
         *     unknown channel and a node whose system this server cannot place all
         *     return the same `update_available: false` shape — a node's client treats
         *     any other status as an error and never parses it, so `204` here would
         *     read as a broken server.
         *
         *     Answers carry an `ETag`; a node SHOULD send `If-None-Match` and handle
         *     `304`. The ETag is omitted when the server deliberately withheld a
         *     cacheable answer, so the node keeps asking.
         */
        get: operations["checkForUpdate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/update/download/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the bundle for a version.
         * @description Supports `Range` and `If-None-Match`; a conditional request takes
         *     precedence over a range (RFC 9110). Nodes resume interrupted downloads,
         *     so range support is load-bearing rather than a nicety.
         */
        get: operations["downloadRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/update/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tell the server how an update went.
         * @description Never rejected on schema. A node that reports badly still reports
         *     something, and losing the sighting is worse than storing a row with a
         *     missing field.
         */
        post: operations["reportOutcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trade the refresh cookie for a new access token.
         * @description One session model for both kinds of sign-in: the page calls this on load
         *     and never learns whether a local account or Keycloak produced the token.
         *     Requires `X-Requested-With: fetch` — a plain HTML form cannot set it,
         *     which is what makes it a CSRF defence.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who this session is, and what it may do.
         * @description `scopes` exists so the UI can hide what it may not use. Without it a
         *     publisher is shown a Promote button that answers 403, which reads as a
         *     broken page rather than as a permission they do not have.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Should the sign-in page offer Keycloak?
         * @description Unauthenticated by definition — the page asks before anyone holds a credential.
         */
        get: operations["oidcStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/oidc/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin the Keycloak redirect.
         * @deprecated
         * @description Server-side Authorization Code exchange, kept for the previous admin UI.
         *     The replacement UI is a PUBLIC client doing PKCE in the browser, which
         *     removes the client secret instead of hiding it. Remove once no deployment
         *     serves the old bundle.
         */
        get: operations["oidcStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where the issuer sends the browser back to.
         * @deprecated
         */
        get: operations["oidcCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * May this server be signed up for?
         * @description Says only yes or no — an anonymous caller has no business learning which half of the configuration is missing.
         */
        get: operations["registrationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account with no credential presented.
         * @description Off unless `ALLOW_SELF_REGISTRATION`. The role is never taken from the
         *     body — it is always `KEYCLOAK_DEFAULT_ROLE`, which opens nothing here
         *     while `OIDC_ADMIN_ROLE` is enforced.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything the admin UI's first screen needs. */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/artifacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        /** One artifact, with what inspection found inside it. */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        /**
         * Remove an artifact. Requires `catalog:delete`.
         * @description Refused while any channel serves the release it belongs to, for the same
         *     reason a whole release is: removing the only artifact a platform is served
         *     from tells every device on that channel there is no update, with no error.
         */
        delete: operations["deleteArtifact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/artifacts/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        /** What changes against the release below this one. */
        get: operations["getArtifactDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/artifacts/{id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Amend an artifact's metadata. Requires `artifact:write`. */
        put: operations["setArtifactMetadata"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/systems/{system}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["SystemPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a release row in a system. Requires `artifact:write`.
         * @description A release is identified by its system AND its version: two systems
         *     may publish the same number. `system` is taken from the path and
         *     refused in the body.
         */
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/systems/{system}/releases/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["SystemPath"];
                version: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a release. Requires `catalog:delete`.
         * @description Refused while any channel serves the release. A channel pointing at nothing
         *     answers every device "no update", which looks exactly like a fleet that is up
         *     to date — so point the channel at another release first. Files are removed
         *     after the commit.
         */
        delete: operations["deleteRelease"];
        options?: never;
        head?: never;
        /** Amend a release. Requires `artifact:write`. */
        patch: operations["updateRelease"];
        trace?: never;
    };
    "/admin/api/systems/{system}/releases/{version}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["SystemPath"];
                version: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One-shot upload against a known system and version, for a scripted caller.
         * @description Both are cross-checked against the bundle, and a mismatch is refused.
         *     The system in the path is used only when the bundle names none.
         */
        post: operations["uploadArtifactToRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** One-shot upload, version taken from the bundle, for a scripted caller. */
        post: operations["uploadArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step one — stage a bundle so an operator can look before committing.
         * @description Nothing is stored yet and the response says so with `stored: false`.
         *     Without that flag the screen reads as done, because it looks exactly like
         *     the one that used to come after the write.
         */
        post: operations["stageUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/uploads/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step two — commit what was staged, onto the staging channel.
         * @description Takes no target channel. A release lands on `beta` and reaches `stable`
         *     only when an admin promotes it, so the person uploading does not choose
         *     where it goes.
         *
         *     It can still be refused for moving `beta` backwards, like every other
         *     path that points a channel somewhere.
         */
        post: operations["commitUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSystems"];
        put?: never;
        /** Create a system. Requires `system:write`. */
        post: operations["createSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/systems/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSystem"];
        options?: never;
        head?: never;
        patch: operations["updateSystem"];
        trace?: never;
    };
    "/admin/api/systems/{system}/channels/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: string;
                name: string;
            };
            cookie?: never;
        };
        get: operations["getChannel"];
        /**
         * Point a channel at a version. Requires `channel:write`.
         * @description **The only operation in this API that reaches an aircraft.** Everything
         *     else adds to a catalog nobody is served from. That is why `channel:write`
         *     is a scope of its own: an engineer uploads, and the admin who reviewed
         *     the build is who moves the channel. A leaked publisher token stages a
         *     file; it does not ship firmware.
         */
        put: operations["putChannel"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/unclassified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nodes whose claimed system this server does not have. */
        get: operations["listUnclassified"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/unclassified/{serial}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serial: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Place a node into a system. Requires `system:write`.
         * @description The only way to classify a device whose version this server never
         *     published — a factory-fresh unit, or one flashed by hand. Send
         *     `{"system": null}` to put it back in the pending list. Nothing resolves
         *     itself with time.
         */
        put: operations["assignNode"];
        post?: never;
        delete: operations["forgetNode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["fleetInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the fleet reported back. */
        get: operations["rolloutReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Accounts in the Keycloak realm. Requires `user:admin`.
         * @description Answers `configured: false` rather than an error when Keycloak is not wired up, so the UI can hide the panel instead of showing a broken one.
         */
        get: operations["listUsers"];
        put?: never;
        /** Create a realm account. Requires `user:admin`. */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/users/{username}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * The second half of a demotion. Requires `user:admin`.
         * @description Keycloak stops granting the role; this stops the token that still claims
         *     it. Cutting sessions does not remove a role — it only stops an old token
         *     from carrying one.
         */
        delete: operations["revokeUserSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The shared fleet keys. Requires `signing_key`.
         * @description Every read is audited. The key is SHARED — every node presents the same
         *     string, so seeing it is equivalent to being able to impersonate any node,
         *     and rotating it means re-provisioning the whole fleet.
         */
        get: operations["fleetApiKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/signing-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The OTA signing key's public half. Requires `signing_key`.
         * @description The exact string an operator provisions into a node's `key_id → public key` map.
         */
        get: operations["signingKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/signing-key/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Store a root-signed certificate for a signing key.
         * @description The root signs it OFFLINE; this server only verifies it against the root's public half and stores it.
         */
        put: operations["putSigningKeyCertificate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/tls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The certificate this server presents, and its fingerprint. */
        get: operations["tlsInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The envelope every failure uses, on BOTH surfaces. Named `error` rather
         *     than `code` because the node protocol froze it that way.
         */
        Error: {
            error: components["schemas"]["ErrorCode"];
            /** @description Prose for a person. May be reworded at any time — branch on `error`, never on this. */
            message: string;
            /** @description Present on validation failures; the findings that caused the refusal. */
            details?: components["schemas"]["Finding"][];
        };
        /**
         * @description A CLOSED enum. Statuses the node protocol never named (403, 405, 409,
         *     413, 415, 426) keep their correct HTTP status but reuse the nearest legal
         *     code, so a conforming node never sees a code it cannot branch on.
         * @enum {string}
         */
        ErrorCode: "missing_parameter" | "invalid_parameter" | "invalid_api_key" | "not_found" | "range_not_satisfiable" | "rate_limited" | "server_error" | "maintenance";
        /**
         * @description Dotted numeric. Compared NUMERICALLY — `1.10.0` is above `1.9.0`, which string ordering gets wrong.
         * @example 1.4.2
         */
        Version: string;
        /** @description One of the thirteen platforms the protocol names. Case matters, because it matters to the node. */
        Platform: string;
        CheckResponse: components["schemas"]["NoUpdate"] | components["schemas"]["Manifest"];
        NoUpdate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            update_available: "NoUpdate";
            channels?: components["schemas"]["Channels"];
        };
        /**
         * @description `signature` covers exactly six fields, joined by newlines with no trailing
         *     newline: version, size, sha256, target, min_version, published_at — the
         *     last two contributing an empty string when absent. Every other key here
         *     is a SIBLING of the signature and changes no signed byte. Adding one is
         *     safe; making one signed is not.
         */
        Manifest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            update_available: "Manifest";
            version: components["schemas"]["Version"];
            /** @description Absolute when `PUBLIC_BASE_URL` is set, relative otherwise. Behind the gateway it MUST be the public URL, or no node can fetch it. */
            url: string;
            size: number;
            sha256: string;
            /** @description Canonical sorted platform target. */
            target: string;
            min_version?: components["schemas"]["Version"];
            mandatory: boolean;
            notes?: string;
            /** Format: date-time */
            published_at?: string;
            /** @description Ed25519 over the six-field payload */
            signature: string;
            /** @description Omitted entirely when no certificate has been uploaded for this key, which is what keeps older deployments unchanged. */
            key_certificate?: string;
            system?: string;
            channels?: components["schemas"]["Channels"];
        };
        /**
         * @description A FLAT array of names, sent on both response shapes. The node reads it
         *     with a string-only check, so objects would be silently dropped. It is
         *     what lets a node sitting on a channel this server does not have be
         *     corrected at all.
         */
        Channels: string[];
        /** @description Never rejected on schema — a badly-formed report is still a sighting. */
        Report: {
            serial?: string;
            version?: components["schemas"]["Version"];
            platform?: components["schemas"]["Platform"];
            /** @description Anything other than success counts against the release. */
            status?: string;
            error?: string;
        } & {
            [key: string]: unknown;
        };
        Session: {
            access_token: string;
            expires_in: number;
            user: {
                [key: string]: unknown;
            };
        };
        Me: {
            id: string | number;
            username: string;
            /** Format: date-time */
            last_login_at?: string | null;
            /** @description Sorted, so the response is stable. */
            scopes: components["schemas"]["Scope"][];
        };
        /** @enum {string} */
        Scope: "self" | "catalog:read" | "artifact:write" | "channel:write" | "catalog:delete" | "system:write" | "user:admin" | "signing_key";
        NewUser: {
            username: string;
            /** Format: email */
            email?: string;
            /** Format: password */
            password: string;
        };
        CreatedAccount: {
            username?: string;
            email?: string;
            role?: string | null;
            note?: string;
        };
        System: {
            name: string;
            description?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        Channel: {
            system?: string;
            name?: string;
            latest?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        ChannelMoved: {
            system?: string;
            name?: string;
            latest?: string;
            /** @description Channels this version was taken off, so the caller can say what else moved. */
            released?: string[];
        };
        Artifact: {
            id: number;
            system: string;
            version: components["schemas"]["Version"];
            kind?: string | null;
            platform: components["schemas"]["Platform"];
            platforms?: components["schemas"]["Platform"][];
            file?: string;
            size: number;
            sha256: string;
            pre_signed?: boolean;
            /** Format: date-time */
            uploaded_at?: string;
            uploaded_by?: string | null;
            /** @description NULL means the row predates bundle inspection, which is not the same as `legacy`. */
            bundle_format?: string | null;
            warning_count?: number;
            plugins?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            inspection?: components["schemas"]["Inspection"] | null;
        };
        /**
         * @description What changes if this artifact is promoted, against the release below it in the
         *     same system. Nothing else in the system answers "what am I actually shipping?" —
         *     the node reports per-component skips with no top-level error, so a release that
         *     changes nothing looks exactly like one that changes everything.
         *
         *     Field casing is mixed and deliberately reported as it is: the service emits
         *     camelCase, and `no_op` is added by the controller.
         */
        Diff: {
            /** @description The release compared against. NULL when this is the first in its system. */
            previousVersion: string | null;
            isFirst: boolean;
            /** @description Present when a previous release exists but carries nothing comparable. */
            noComparable?: boolean;
            platforms: {
                added?: components["schemas"]["Platform"][];
                removed?: components["schemas"]["Platform"][];
            };
            cores: components["schemas"]["CoreMove"][];
            plugins: components["schemas"]["PluginMove"][];
            config: components["schemas"]["ConfigMove"][];
            /**
             * @description True when this release changes nothing. Computed from the three lists above,
             *     and false whenever there is nothing to compare against — being first is not
             *     the same as changing nothing.
             */
            no_op: boolean;
        };
        CoreMove: {
            platform?: components["schemas"]["Platform"];
            /** @description NULL when the platform is new to this line. */
            from?: string | null;
            to?: string;
            /** @enum {string} */
            change?: "added" | "updated";
        };
        PluginMove: {
            platform?: components["schemas"]["Platform"];
            name?: string;
            /** @enum {string} */
            change?: "added" | "removed" | "changed" | "unchanged";
            from?: string | null;
            to?: string | null;
        };
        ConfigMove: {
            platform?: components["schemas"]["Platform"];
            /** @description The file or component the parameter belongs to. */
            target?: string;
            param?: string;
            /** @enum {string} */
            change?: "added" | "removed" | "changed" | "unchanged";
            from?: unknown;
            to?: unknown;
        };
        /**
         * @description A machine-readable note from bundle inspection, used for both warnings and the
         *     findings attached to a refusal. Branch on `rule`; `message` is prose for a person.
         */
        Finding: {
            /**
             * @description Stable name of the check. `config_only_needs_platforms` is the one a client
             *     must handle: a bundle carrying only configuration names no target platforms,
             *     and the operator has to supply them before it can be staged.
             *     `channel_rollback` is the other: the channel would move backwards, and the
             *     caller may proceed by re-sending with `allow_rollback`.
             *     `release_in_use` refuses removing a build a channel is serving;
             *     `channels` names every channel serving it.
             */
            rule: string;
            message: string;
            /**
             * @description `channel_rollback` only — the version the channel is on now. Absent on findings
             *     that describe a bundle rather than a move, which is why it is not required.
             */
            from?: string;
            /** @description `channel_rollback` only — the version the move would point it at. */
            to?: string;
            /**
             * @description `release_in_use` only — every `system/channel` serving the release, current at
             *     the moment of the refusal. Show these rather than a list from an earlier
             *     catalog fetch.
             */
            channels?: string[];
        };
        /**
         * @description What the server read out of a bundle. Presented to an operator before anything is
         *     stored, so every field here is something a person is expected to act on.
         */
        Inspection: {
            format?: string | null;
            version?: string | null;
            platforms?: components["schemas"]["Platform"][];
            cores?: components["schemas"]["InspectedCore"][];
            plugins?: components["schemas"]["InspectedPlugin"][];
            configs?: components["schemas"]["ShippedConfigFile"][];
            release?: components["schemas"]["BundleRelease"];
            warnings?: components["schemas"]["Finding"][];
        };
        InspectedCore: {
            platform?: components["schemas"]["Platform"];
            path?: string;
            slice_version?: string | null;
            /** @description The system this slice was stamped for; what a bundled plugin has to cover. */
            system?: string | null;
            bundled_plugins?: components["schemas"]["BundledPlugin"][];
            shipped_config?: components["schemas"]["ShippedConfigFile"][];
        };
        /** @description A plugin riding inside a core slice. Named separately rather than filed under the core, because which product it covers is a different question from where it sits. */
        BundledPlugin: {
            name?: string;
            version?: string | null;
            version_known?: boolean;
            /** @description Products this plugin declares itself valid on. EMPTY MEANS EVERYTHING, the same reading the node gives it. */
            systems?: string[];
        };
        InspectedPlugin: {
            name?: string;
            platform?: components["schemas"]["Platform"];
            path?: string;
            version?: string | null;
            version_known?: boolean;
            systems?: string[];
            shipped_config?: components["schemas"]["ShippedConfigFile"][];
        };
        /**
         * @description One configuration file the bundle ships. A file with no params is still recorded:
         *     it is not a config file, but it still replaces whatever the node has.
         */
        ShippedConfigFile: {
            file?: string;
            /** @description The plugin it belongs to */
            plugin?: string | null;
            params?: components["schemas"]["ConfigParam"][];
        };
        ConfigParam: {
            /** @description Dotted `group.key`. */
            param?: string;
            value?: unknown;
            /**
             * @description A locked parameter keeps the node's own value and will NOT be applied. This is
             *     why an operator must see locked and unlocked apart — the two halves of a config
             *     payload have opposite effects on a device.
             */
            locked?: boolean;
            readonly?: boolean;
        };
        /** @description Release metadata from an optional release.json at the archive root — the only metadata the bundle manifest cannot carry. camelCase, as the code emits it. */
        BundleRelease: {
            system?: string | null;
            minVersion?: string | null;
            mandatory?: boolean;
            notes?: string | null;
            configDropped?: string[];
        };
        StagedUpload: {
            token: string;
            version?: components["schemas"]["Version"];
            system?: string | null;
            kind?: string | null;
            platform?: components["schemas"]["Platform"];
            platforms?: components["schemas"]["Platform"][];
            size?: number;
            sha256?: string;
            /**
             * @description Nothing is written yet. Without this the panel reads as done, because it looks exactly like the one that comes after the write.
             * @constant
             */
            stored: false;
            diff?: components["schemas"]["Diff"];
            inspection?: components["schemas"]["Inspection"];
        };
        CommittedUpload: components["schemas"]["Artifact"] & {
            release_created?: boolean;
            promoted_to?: string | null;
            system?: string | null;
            /** @constant */
            stored?: true;
            diff?: components["schemas"]["Diff"];
            inspection?: components["schemas"]["Inspection"];
        };
        /** @description A row of `unclassified_node` — a device this server has seen but cannot place. */
        UnclassifiedNode: {
            serial?: string;
            platform?: components["schemas"]["Platform"];
            version?: components["schemas"]["Version"];
            role?: string | null;
            channel?: string | null;
            fleet?: string | null;
            /**
             * @description What the node said it was, from its own manifest. NULL means it sent
             *     nothing at all, which is a DIFFERENT situation from naming a system
             *     this server does not have: the first is a build that was never
             *     stamped, the second is a misconfiguration. A screen that collapses
             *     the two sends an operator looking in the wrong place.
             */
            reported_system?: string | null;
            /** Format: date-time */
            first_seen?: string;
            /** Format: date-time */
            last_seen?: string;
            seen_count?: number;
            /** @description NULL while the node is still pending an admin's decision. Nothing resolves itself with time. */
            assigned_system?: string | null;
            /** Format: date-time */
            assigned_at?: string | null;
            assigned_by?: string | null;
        };
        SigningKey: {
            key_id?: string;
            /** @description NULL under `SIGNING_REQUIRE_PRESIGNED`, where there is no local key pair at all. That is the goal state, not an error. */
            public_key_base64?: string | null;
            /** @constant */
            algorithm?: "ed25519";
            key_file?: string | null;
            holds_private_key?: boolean;
            root_key_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        Catalog: {
            revision?: string | number;
            systems?: components["schemas"]["System"][];
            unclassified_pending?: number;
            channels?: components["schemas"]["Channel"][];
            /** @description Channels pointing at a system that no longer defines them. They serve nothing, silently — the failure that looks like a working rollout. */
            stray_channels?: {
                system?: string;
                channel?: string;
                /**
                 * @description How many DISTINCT serials asked for it in the window. This is the
                 *     difference between a stale row and an incident happening now — a
                 *     banner listing only names cannot tell an operator which it is.
                 */
                nodes?: number;
                /**
                 * Format: date-time
                 * @description The most recent check-in for this system/channel pair.
                 */
                last_seen?: string;
            }[];
            releases?: ({
                version?: components["schemas"]["Version"];
                system?: string;
                artifacts?: components["schemas"]["Artifact"][];
            } & {
                [key: string]: unknown;
            })[];
        };
        /**
         * @description The most recent check-in per serial, from `check_log`. This is a
         *     SIGHTING, not an inventory: a node appears here because it asked, so a
         *     device that has stopped asking keeps its last row and looks healthy.
         *     Read `at` before reading anything else.
         */
        FleetNode: {
            serial?: string;
            platform?: components["schemas"]["Platform"];
            version?: components["schemas"]["Version"];
            role?: string | null;
            channel?: string | null;
            /** @description The version the server offered on that check, or NULL when it offered nothing. */
            offered?: string | null;
            update_available?: boolean;
            /** Format: date-time */
            at?: string;
            system?: string | null;
        };
        /**
         * @description Reports grouped by outcome and error text, most common first. Anything
         *     other than `success` counts against the release — the group is the unit
         *     an operator judges a rollout by.
         */
        RolloutStat: {
            result?: string;
            /** @description `(none)` when the node reported no error text, so the group is never keyed on an empty string. */
            error?: string;
            count?: number;
        };
        /** @description One row of `node_report` — what a single node said happened. */
        NodeReport: {
            id?: number;
            serial?: string;
            platform?: components["schemas"]["Platform"];
            role?: string | null;
            from_version?: string | null;
            to_version?: string | null;
            result?: string;
            error?: string | null;
            /**
             * Format: date-time
             * @description When the node says it happened. Node clocks are not trustworthy; `received_at` is this server's own.
             */
            at?: string | null;
            /** Format: date-time */
            received_at?: string;
        };
        /**
         * @description Actions worth keeping a trace of, including reads — fetching the fleet
         *     API keys is audited even though the caller is already an authenticated
         *     admin, because the key is shared and seeing it is equivalent to holding it.
         */
        AuditEntry: {
            id?: number;
            /** Format: date-time */
            at?: string;
            actor?: string;
            action?: string;
            subject?: string | null;
            /** @description Never a password, and never its length. */
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description An account as Keycloak reports it (brief representation). Roles are NOT
         *     here: they live in the realm and this server only reads them off a
         *     presented token, so this list cannot say what any of these accounts may
         *     do on this server.
         */
        RealmUser: {
            id?: string;
            username?: string;
            /** Format: email */
            email?: string | null;
            enabled?: boolean;
            /** Format: date-time */
            created_at?: string | null;
        };
        /**
         * @description Parsed out of `UPDATE_API_KEYS`, never out of the database. An entry with
         *     no `name:` prefix is given a positional name (`fleet-1`).
         */
        FleetApiKey: {
            fleet?: string;
            /** @description The literal credential. Shared by every node in that fleet — this response is why the read is audited. */
            key?: string;
        };
        /**
         * @description The certificate captured at boot, so the UI can say what browsers and
         *     nodes must be told to trust. The private key is stripped before this is
         *     ever stored, so it cannot leak through here.
         */
        TlsInfo: {
            /** @description False only when the server never completed TLS setup; every other field is then absent. */
            enabled: boolean;
            /** @description True when this server made the certificate itself on first boot. */
            generated?: boolean;
            subject?: string;
            issuer?: string;
            validFrom?: string;
            validTo?: string;
            /** @description What an operator pins on a node, and what the boot log prints. */
            fingerprint256?: string;
            /**
             * @description Empty is the usual reason the UI works on localhost and nothing else:
             *     a certificate that does not name the address a client dials fails
             *     verification there, and a node with TLS rejects it outright with no
             *     way to click through.
             */
            subjectAltName?: string;
            selfSigned?: boolean;
            daysRemaining?: number | null;
        };
        OidcStatus: {
            /** @description Whether this server has an issuer configured at all. */
            enabled: boolean;
            /**
             * @description Whether that issuer answered just now. The sign-in page needs BOTH:
             *     with no provider reachable there is no way to sign in at all, and
             *     the page must say so rather than offer a button that redirects into
             *     an outage.
             */
            reachable: boolean;
        };
    };
    responses: {
        /** @description Done. */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @constant */
                    ok?: true;
                };
            };
        };
        /** @description Malformed or missing parameter. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No credential, or one this server does not accept. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated, but this principal lacks the scope the operation needs. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such thing. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Already exists. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Bigger than `UPLOAD_MAX_BYTES`. */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many attempts from this source. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Refusing everything but health while publishing. */
        Maintenance: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Limit: number;
        ArtifactId: number;
        SystemPath: string;
        VersionPath: components["schemas"]["Version"];
        /** @description Must be `fetch`. A plain HTML form cannot set a custom header, which is what makes this a CSRF defence. */
        FetchHeader: "fetch";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status?: "ok";
                    };
                };
            };
        };
    };
    checkForUpdate: {
        parameters: {
            query: {
                /** @description The node's own serial. Recorded, and used to pin a node to a release. */
                serial: string;
                platform: components["schemas"]["Platform"];
                /** @description What the node is running now, dotted numeric. Compared NUMERICALLY, never as a string. */
                version: components["schemas"]["Version"];
                /**
                 * @description The system the node is, from its own manifest. Required: two systems
                 *     may publish the same version number, so the version alone does not
                 *     say which product is asking. Absent or blank — a build that was never
                 *     stamped — is `400 missing_parameter`. A name this server does not know
                 *     is NOT an error: the server offers nothing and records the sighting
                 *     for an admin to place.
                 */
                system: string;
                /** @description Defaults to `stable`. A credential scoped to other channels is REFUSED, not redirected. */
                channel?: string;
                /** @description What the node already has, as `Name@1.2.0,Other@2.0.1`. */
                plugins?: string;
            };
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The answer, whether or not there is an update. */
            200: {
                headers: {
                    /** @description Absent when the answer was deliberately not cacheable. */
                    ETag?: string;
                    "Cache-Control"?: "no-cache";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            /** @description Unchanged since the caller's ETag. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /**
             * @description This credential does not follow the channel that was asked for.
             *     Refused rather than quietly served another channel: a device handed
             *     something nobody chose for it would report success and hide the
             *     mistake.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["Maintenance"];
        };
    };
    downloadRelease: {
        parameters: {
            query: {
                platform: components["schemas"]["Platform"];
                /**
                 * @description Which system's release this is. A version names a release only
                 *     together with its system. The check response hands out this URL
                 *     complete; a caller never composes it.
                 */
                system: string;
            };
            header?: {
                Range?: string;
                "If-None-Match"?: string;
            };
            path: {
                version: components["schemas"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole bundle. */
            200: {
                headers: {
                    ETag?: string;
                    "Accept-Ranges"?: "bytes";
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/gzip": string;
                };
            };
            /** @description The requested byte range. */
            206: {
                headers: {
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/gzip": string;
                };
            };
            /** @description Unchanged since the caller's ETag. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The range lies beyond the end of the artifact. */
            416: {
                headers: {
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reportOutcome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Report"];
            };
        };
        responses: {
            /** @description Recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok?: true;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Must be `fetch`. A plain HTML form cannot set a custom header, which is what makes this a CSRF defence. */
                "X-Requested-With": components["parameters"]["FetchHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A fresh access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in principal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Must be `fetch`. A plain HTML form cannot set a custom header, which is what makes this a CSRF defence. */
                "X-Requested-With": components["parameters"]["FetchHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    oidcStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether Keycloak is configured, and whether it is answering. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OidcStatus"];
                };
            };
        };
    };
    oidcStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Off to the issuer. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oidcCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    registrationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether self-service sign-up is on. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        enabled?: boolean;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewUser"];
            };
        };
        responses: {
            /** @description Created in the realm. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedAccount"];
                };
            };
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The artifact. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed, with its file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description A channel is serving the release this artifact belongs to. `details`
             *     carries a finding with `rule: release_in_use` and the `channels`.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getArtifactDiff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The diff. `no_op` is true when this release changes nothing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diff"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setArtifactMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description The amended artifact. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["SystemPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["SystemPath"];
                version: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed, with every artifact in it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        system: string;
                        version: components["schemas"]["Version"];
                        /** @description How many artifacts went with it. */
                        artifacts: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description A channel is serving this release. `details` carries a finding with
             *     `rule: release_in_use` and the `channels`, so a caller can say which one
             *     to move without parsing the message.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["SystemPath"];
                version: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Amended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    uploadArtifactToRelease: {
        parameters: {
            query?: {
                /**
                 * @description Point this channel at the uploaded release, in the same transaction.
                 *
                 *     Omitted, the release lands on the automatic promotion target. Present
                 *     and empty, it lands nowhere. Naming any channel other than the staging
                 *     channel requires `channel:write` — uploading fills the catalog, moving
                 *     a channel is what reaches an aircraft, and they are deliberately
                 *     different rights.
                 */
                channel?: string;
                /**
                 * @description Proceed even though the named channel would move backwards. Requires
                 *     `channel:write`, like naming a channel does: it is meaningless without it.
                 */
                allow_rollback?: boolean;
                /** @description Cross-checked against the bundle manifest; a mismatch is refused. */
                kind?: "fleet" | "slim";
                /** @description Comma-separated. Cross-checked against the bundle manifest. */
                platforms?: string;
            };
            header?: never;
            path: {
                system: components["parameters"]["SystemPath"];
                version: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/gzip": string;
            };
        };
        responses: {
            /** @description Stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["TooLarge"];
        };
    };
    uploadArtifact: {
        parameters: {
            query?: {
                /**
                 * @description Point this channel at the uploaded release, in the same transaction.
                 *
                 *     Omitted, the release lands on the automatic promotion target. Present
                 *     and empty, it lands nowhere. Naming any channel other than the staging
                 *     channel requires `channel:write` — uploading fills the catalog, moving
                 *     a channel is what reaches an aircraft, and they are deliberately
                 *     different rights.
                 */
                channel?: string;
                /**
                 * @description Proceed even though the named channel would move backwards. Requires
                 *     `channel:write`, like naming a channel does: it is meaningless without it.
                 */
                allow_rollback?: boolean;
                /** @description Cross-checked against the bundle manifest; a mismatch is refused. */
                kind?: "fleet" | "slim";
                /** @description Comma-separated. Cross-checked against the bundle manifest. */
                platforms?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/gzip": string;
            };
        };
        responses: {
            /** @description Stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["TooLarge"];
        };
    };
    stageUpload: {
        parameters: {
            query?: {
                kind?: string;
                platforms?: string;
            };
            header?: {
                /** @description Refuse the upload unless the bytes hash to this. */
                "X-Expected-SHA256"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/gzip": string;
            };
        };
        responses: {
            /** @description Staged, not stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedUpload"];
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["TooLarge"];
        };
    };
    commitUpload: {
        parameters: {
            query?: {
                /** @description Proceed even though the staging channel would move backwards. */
                allow_rollback?: boolean;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommittedUpload"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listSystems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every system. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        systems?: components["schemas"]["System"][];
                    };
                };
            };
        };
    };
    createSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string;
                };
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["System"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    deleteSystem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateSystem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Amended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["System"];
                };
            };
        };
    };
    getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Where the channel points. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: components["schemas"]["Version"];
                };
            };
        };
        responses: {
            /** @description Moved. `released` names the channels this version was taken off. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelMoved"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listUnclassified: {
        parameters: {
            query?: {
                filter?: "pending" | "assigned" | "all";
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The nodes waiting to be placed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        nodes?: components["schemas"]["UnclassifiedNode"][];
                    };
                };
            };
        };
    };
    assignNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serial: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    system?: string | null;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    forgetNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serial: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            404: components["responses"]["NotFound"];
        };
    };
    fleetInventory: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every node that has checked in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        nodes?: components["schemas"]["FleetNode"][];
                    };
                };
            };
        };
    };
    rolloutReports: {
        parameters: {
            query?: {
                version?: components["schemas"]["Version"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roll-up plus the most recent rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: string | null;
                        stats?: components["schemas"]["RolloutStat"][];
                        recent?: components["schemas"]["NodeReport"][];
                    };
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The accounts, or a flag saying there is no realm to ask. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configured?: boolean;
                        users?: components["schemas"]["RealmUser"][];
                    };
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewUser"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedAccount"];
                };
            };
        };
    };
    revokeUserSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        username?: string;
                        note?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    fleetApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The configured keys, with that warning in the payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys?: components["schemas"]["FleetApiKey"][];
                        /** @constant */
                        shared?: true;
                        note?: string;
                    };
                };
            };
        };
    };
    signingKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The key, or a statement that this server holds no private half. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SigningKey"];
                };
            };
        };
    };
    putSigningKeyCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["BadRequest"];
        };
    };
    auditLog: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent audited actions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries?: components["schemas"]["AuditEntry"][];
                    };
                };
            };
        };
    };
    tlsInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TLS material. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TlsInfo"];
                };
            };
        };
    };
}
